export type Item = {
  uid: string;
  level: number;
  type: string;
  subtype: string | null;
  xp: number;
  craftXp: number;
  value: number;
  tradeMinMaxValue: string | null;
  favor: number;
  time: number;
  atk: number;
  def: number;
  hp: number;
  eva: string;
  crit: string;
  excl: string | null;
  tier: number;
  subtier: number;
  combo: number;
  worker1: string;
  worker2: string | null;
  worker3: string | null;
  w1BuildingReq: number;
  w2BuildingReq: number;
  w3BuildingReq: number;
  resource1: string;
  r1Qty: number;
  resource2: string | null;
  r2Qty: number;
  resource3: string | null;
  r3Qty: number;
  component1: string | null;
  c1Qty: number;
  c1Tags: string | null;
  component2: string | null;
  c2Qty: number;
  c2Tags: string | null;
  u1Req: number;
  u2Req: number;
  u3Req: number;
  u4Req: number;
  u5Req: number;
  upgrade1: string;
  upgrade2: string;
  upgrade3: string;
  upgrade4: string;
  upgrade5: string;
  upgradeBonus: number;
  supgrade1: string;
  supgrade2: string;
  supgrade3: string;
  su1Cost: number;
  su2Cost: number;
  su3Cost: number;
  restrict: string | null;
  reqTags: string | null;
  tagIndex: number;
  elements: string | null;
  skill: string | null;
  lTag2: string | null;
  lTag3: string | null;
  elementAffinity: string | null;
  spiritAffinity: string | null;
  tag: string | null;
  discount: number;
  surcharge: number;
  suggest: number;
  speedup: number;
  buyAnimIdOverride: number;
  questAnimIdOverride: number;
  slotOverride: string | null;
  soundType: string;
  unlock: number;
  chest: string | null;
  firstOfLine: boolean;
  prohibited: boolean;
  hasChinaTexture: boolean;
  nonCraftable: boolean;
  releaseAt: string | null;
  shardPrice: number;
  capriceDelay: number;
  EnchantedItemTexturer: boolean;
  isTitanItem: boolean;
};

export type MarketPrice = {
  id: number;
  tType: string;
  uid: string;
  tag1: string;
  tag2: string;
  tag3: string;
  goldQty: number;
  gemsQty: number;
  created: string;
  tier: number;
  order: number;
  cityId: number;
  goldPrice: number | null;
  gemsPrice: number | null;
  requestCycleLast: number;
  createdAt: string;
  updatedAt: string;
};
