export type SearchParams = Record<string, string>;

export interface Option {
  label: string;
  value: string;
  icon?: React.ComponentType<{ className?: string }>;
  withCount?: boolean;
}

export interface DataTableFilterField<TData> {
  label: string;
  value: keyof TData;
  placeholder?: string;
  options?: Option[];
}

export interface DataTableFilterOption<TData> {
  id: string;
  label: string;
  value: keyof TData;
  options: Option[];
  filterValues?: string[];
  filterOperator?: string;
  isMulti?: boolean;
}

export type SessionData = {
  user?: XSollaUser;
  token?: string;
};

export type XSollaUser = {
  id: string;
  username: string | null;
  nickname: string | null;
  name: string | null;
  tag: string | null;
  picture: string | null;
  birthday: string | null;
  first_name: string | null;
  last_name: string | null;
  gender: string | null;
  email: string | null;
  phone: string | null;
  phone_auth: string | null;
  groups: {
    id: number;
    name: string;
    is_default: boolean;
    is_deletable: boolean;
  }[];
  registered: string;
  external_id: string | null;
  last_login: string;
  ban:
    | {
        date_from: string;
        date_to: string;
        reason: string;
      }[]
    | null;
  country: string | null;
  connection_information: string | null;
  is_anonymous: boolean;
  devices: {
    id: number;
    type: string;
    device: string;
    last_used_at: string;
  };
  is_last_email_confirmed: boolean | null;
  is_user_active: boolean;
};

export type User = {
  id: string;
  uuid: string;
  name: string;
  lvl: number;
};

export type Account = {
  user: {
    _id: string;
    isChinaMinor: boolean;
    secret: string;
    name: string;
    nameChanges: number;
    ticks: number;
    wticks: number;
    wpaused: number;
    srvLck: boolean;
    countryCode: string;
    platform: string;
    authType: string;
    version: number;
    clientVersion: string;
    gold: number;
    gems: number;
    dragonEmblem: number;
    gcoins: number;
    spins: number;
    tokens: number;
    ban: number;
    cban: number;
    tban: number;
    nban: number;
    lban: number;
    tgban: boolean;
    deleteAt: number;
    spinResult: unknown;
    spinCycle: number;
    ofrCycle: number;
    dailyOfr: {
      type: number;
      entId: number;
      uid: string | null;
      val: number;
      seen: boolean;
    };
    dealCycle: number;
    dailyDeal: {
      uid: string | null;
      i1: string | null;
      i1Qty: number;
      i2: string | null;
      i2Qty: number;
      i3: string | null;
      i3Qty: number;
      seen: boolean;
      purchased: boolean;
    };
    bnkCycle: number;
    dailyBnk: {
      type: number;
      target: number;
      progress: number;
      uid: string | null;
      seen: boolean;
      num: number;
    };
    guildChest: unknown;
    tknRrCycle: number;
    vip: number;
    vipCount: number;
    isVip: boolean;
    dailyGemSub: {
      gaveaway: boolean;
    };
    gemSubDuration: number;
    gSubCycle: number;
    lastGemGiveawayDate: number;
    idDevice: string;
    idGameCenter: unknown;
    idGooglePlay: unknown;
    idSteam: unknown;
    idEOS: unknown;
    idFacebook: unknown;
    idKongregate: unknown;
    idGalaxyMx: unknown;
    idWSA: unknown;
    city: string;
    dlCityInv: unknown;
    level: number;
    xp: number;
    mxp: number;
    energy: number;
    layout: string;
    lcraft: number;
    lcraftf: number;
    lhspawn: number;
    lgwleave: number;
    lrmdvleave: number;
    lrwspawn: number;
    lswspawn: number;
    lkspawn: number;
    fkspawn: boolean;
    kingFrmSklEff: boolean;
    fResWorVisUid: unknown;
    fSelWorVisUid: unknown;
    lcrequest: number;
    lcbabandon: number;
    advTokens: unknown;
    invOverflow: boolean;
    flevel: number;
    qlevel: number;
    clevel: number;
    alevel: number;
    tlevel: number;
    plevel: number;
    created: number;
    grndLyrId: number;
    sseed: string;
    wid: number;
    stats: {
      lvl: number;
      bp: number;
      gld: number;
      sll: number;
      buy: number;
      cft: number;
      cftgc: number;
      ecft: number;
      qst: number;
      qsts: unknown;
      boss: unknown;
      prest: number;
      help: number;
      invst: number;
      trd: number;
      clsTypLvls: unknown;
      itmTypLvls: unknown;
      qstLvls: unknown;
      activity: number;
      chests: unknown;
      bigSale: number;
      tutorial: number;
      argon: number;
      sia: number;
      yami: number;
      lilu: number;
      rudo: number;
      polonia: number;
      donovan: number;
      hemma: number;
      ashley: number;
      bjorn: number;
      hhired: number;
      alevel: number;
      whired: number;
      flevel: number;
      energy: number;
      dpurchased: number;
      cres: number;
      ures: number;
      rres: number;
      eres: number;
      loot: number;
      bosses: number;
      copened: number;
      research: number;
      ascend: number;
      ascendUpg: number;
      master: number;
      expansions: number;
      bsmtExpansions: number;
      damage: number;
      jackslot: number;
      echt: number;
      echtTwin: number;
      echtLedg: number;
      tunlocked: number;
      bounty: number;
      strAdvId: number;
      strAdvPow: number;
      strAdvClass: unknown;
      gspent: number;
      fuseUncommon: number;
      fuseFlawless: number;
      fuseEpic: number;
      fuseLegend: number;
      masterpiece: number;
      fullMoon: number;
      transmuter: number;
      lg: number;
      collection: number;
      bookEntry: number;
      bpTier: number;
      bpTypHiTiers: unknown;
      goldCityGold: number;
      goldCitySilver: number;
      goldCityBronze: number;
      kingGold: number;
      kingSilver: number;
      kingBronze: number;
      dragonGold: number;
      dragonSilver: number;
      dragonBronze: number;
      customization: number;
      decoration: number;
      talksucc: number;
      talkfail: number;
      marketgems: number;
      marketgold: number;
      power_t: number;
      sellfk: number;
      login: number;
      loginCycle: number;
      accountage: number;
      accountdb: number;
      vip: number;
      tot: number;
      battlepassuid: number;
      battlepassv: number;
      lcog: number;
      tkc: number;
      di: number;
      title: number;
      ascend_l: string | null;
      tot_terror: number;
      petLevel1: number;
      petLevel2: number;
      petLevel3: number;
      dollarspent: number;
    };
    expan: {
      level: number;
      vlevel: number;
      areas: number;
      sareas: number;
      next: number;
      begin: number;
      end: number;
      ahelp: boolean;
      vad: number;
    };
    basement: {
      level: number;
      expanding: boolean;
      begin: number;
      end: number;
      ahelp: boolean;
      vad: number;
    };
    inbox: {
      uid: string;
      wid: number;
      content: unknown;
    };
    notifs: {
      uid: string;
      wid: number;
      content: unknown[];
    };
    shopkprCust: {
      gnd: string;
      cust: {
        bdyTyp: number;
        bdyScl: string;
        hrCut: string;
        brd: string;
        mst: string;
        eyeClr: string;
        hrClr: string;
        skClr: string;
        shrClr: string;
        pntClr: string;
        fclExpr: string;
      };
      hat: string;
      hatClr: string;
      srtClr2: string;
      armor: string;
      shoes: string;
      shoesClr: string;
      cloak: string;
      weapon: string;
      gloves: string;
      glovesClr: string;
      face: string;
      pants: string;
    };
    vtrx: {
      count: number;
      begin: number;
      end: number;
      rate: unknown;
    };
    ocount: {
      count: number;
      begin: number;
      end: number;
      rate: unknown;
    };
    orcount: {
      count: number;
      begin: number;
      end: number;
      rate: unknown;
    };
    initObj: number;
    spnFls: number;
    spnKyFls: number;
    abseed: string;
    invbon: number;
    quEvStartedAt: number;
    quEvClearedAt: number;
    quEvBossLvl: number;
    quEvNxtWins: number;
    quEvUid: unknown;
    quEvSeed: unknown;
    quEvSeedOffset: number;
    quEvId: unknown;
    quEvTier: number;
    quEvTierDef: boolean;
    quEvRewUid: unknown;
    quEvSnProg: number;
    quEvKingPackCycle: number;
    quEvRankChecked: boolean;
    quEvDragonCycle: number;
    quEvDragonAttack: boolean;
    fQuEvId: unknown;
    lastActivity: number;
    collectionSnProg: number;
    battlePassEvId: unknown;
    battlePassEvUid: unknown;
    battlePassPoint: number;
    battlePassSnProg: number;
    battlePassOfferPrice: number;
    battlePassOfferLastSeen: boolean;
    battlePassOfferPurch: boolean;
    battlePassEvEndAt: number;
    snFullMoon: boolean;
    asShop: {
      active: boolean;
      seed: string;
      seenItems0: unknown[];
      seenItems1: unknown[];
      seenItems2: unknown[];
      seenItems3: unknown[];
      seenItems4: unknown[];
      seenItems5: unknown[];
      items: unknown[];
    };
    asShopCycle: number;
    tut: unknown;
    pflags: unknown;
    vflags: unknown;
    lflags: unknown;
    sfflags: {
      f1: number;
      f2: number;
      f3: number;
      f4: number;
      f5: number;
      f6: number;
      f7: number;
      f8: number;
      f9: number;
      f10: number;
      f11: number;
      f12: number;
      f13: number;
      f14: number;
      f15: number;
      f16: number;
      f17: number;
      f18: number;
      f19: number;
      f20: number;
      f21: number;
      f22: number;
      f23: number;
      f24: number;
      f25: number;
      f26: number;
      f27: number;
      f28: number;
      f29: number;
      f30: number;
      f31: number;
      f32: number;
      f33: number;
      f34: number;
      f35: number;
      f36: number;
      f37: number;
      f38: number;
      f39: number;
      f40: number;
      f41: number;
      f42: number;
      f43: number;
      f44: number;
      f45: number;
      f46: number;
      f47: number;
      f48: number;
      f49: number;
      f50: number;
      f51: number;
      f52: number;
      f53: number;
      f54: number;
      f55: number;
      f56: number;
      f57: number;
      f58: number;
      f59: number;
      f60: number;
      f61: number;
      f62: number;
      f63: number;
      f64: number;
      f65: number;
      f66: number;
    };
    sdflags: {
      f1: number;
      f2: number;
      f3: number;
      f4: number;
      f5: number;
      f6: number;
      f7: number;
      f8: number;
      f9: number;
      f10: number;
      f11: number;
      f12: number;
      f13: number;
      f14: number;
      f15: number;
      f16: number;
      f17: number;
      f18: number;
      f19: number;
    };
    spflags: {
      f1: number;
    };
    spcflags: {
      f1: number;
      f2: number;
      f3: number;
      f4: number;
      f5: number;
    };
    ctut: number;
    stut: number;
    otut: unknown;
    options: {
      arack: boolean;
      bspd: number;
      isso: boolean;
      notif: number;
      pnToken: unknown;
      pnPlatform: unknown;
      pnLanguage: string;
      acinv: boolean;
    };
    tknNxt: number;
    tknNxt2: number;
    tknNxt3: number;
    txh: number;
    txg: number;
    txv: number;
    ru: boolean;
    numGChest: number;
    ruShown: number;
    ruNext: number;
    lastonew: number;
    lastonewtp: number;
    lastbslvl: number;
    fUpPurchase: unknown;
    floorsIndex: unknown;
    floorsCust: unknown;
    wallsIndex: unknown;
    wallsCust: unknown;
    beamsCust: string;
    adsEnabled: boolean;
    lastvad: number;
    lastvads: boolean;
    loginEvent: {
      begin: number;
      family: unknown;
      seen: boolean;
      flags: number;
    };
    staticTimeplayed: number;
    staticSignInAt: number;
    cgCycle: number;
    cgLast: unknown;
    cgPending: unknown;
    cgaCycle: number;
    cfvPending: unknown;
    cfvCycle: number;
    cftvCycle: number;
    churnValue: unknown;
    churnReward: boolean;
    churnRolled: boolean;
    churnEnabled: boolean;
    npdTradeGems: number;
    titans: {
      "TITAN:0": Titan;
      "TITAN:1": Titan;
      "TITAN:2": Titan;
      "TITAN:3": Titan;
      "TITAN:4": Titan;
      "TITAN:5": Titan;
    };
    limitsEnabled: boolean;
    limitSR: number;
    limitSRC: number;
    limitCO: number;
    limitCOC: number;
    limitEI: number;
    limitEIC: number;
    limitFC: number;
    limitFCC: number;
    pitiesEnabled: boolean;
    crossDressingEnabled: boolean;
    cplayertitle: unknown;
    afCounter: number;
    afGuid: unknown;
    stPtsUnlocked: number;
    stPtsUnlockedFree: number;
    stPtsSpent: number;
    stPtsSpentFree: number;
    sklL: unknown;
    lrdeem: number;
    returningPlayerRest: number;
    blueprints: {
      uid: string;
      created: number;
    }[];
    inventory: unknown;
    sinventory: unknown;
    visitors: unknown;
    shopkeepers: {
      id: number;
      vstUserId: unknown;
      state: string;
      counterId: number;
    }[];
    furniture: {
      id: number;
      uid: string;
      level: number;
      enabledItemTypesInRackMask: number;
      state: string;
    }[];
    pet: unknown;
    petSpecies: unknown;
    adventurers: unknown;
    heroes: {
      id: number;
      uid: string;
      level: number;
      story: number;
      isTitan: boolean;
      xp: number;
      busy: boolean;
      onShip: boolean;
      ready: number;
      qlast: number;
      rduration: number;
      injured: boolean;
      hired: boolean;
      introduced: boolean;
      cycle: number;
      seen: boolean;
      forceSpawn: boolean;
      blitzSeen: boolean;
      satk: number;
      sdef: number;
      shp: number;
      sfir: number;
      swtr: number;
      sair: number;
      sert: number;
      slgt: number;
      sdrk: number;
      seeds: number;
      hpSeeds: number;
      atkSeeds: number;
      defSeeds: number;
      maxHpSeed: number;
      maxAtkSeed: number;
      maxDefSeed: number;
      maxLvlSeed: number;
      flags: unknown;
      items: unknown;
      transmogs: unknown;
    }[];
    crafts: unknown;
    upgrades: unknown;
    quests: unknown;
    qstatus: {
      uid: string;
      locked: boolean;
      killed: number;
      busy: boolean;
      level: number;
      xp: number;
      qtypes: number;
      targs: number;
      boss: boolean;
      bcycle: number;
      bret: number;
      lastStartedAt1: number;
      lastStartedAt2: number;
      lastStartedAt3: number;
      lastStartedAtBoss: number;
      attemptsFlags: number;
      favQuests: unknown;
    }[];
    workers: Worker[];
    investments: unknown;
    layouts: string[];
    unlocks: unknown;
    fskins: unknown;
    ilocks: unknown;
    wintr: unknown;
    clmdUpgrds: unknown;
    clmdQuEvRes: unknown;
    clmdCoBkRes: unknown;
    clmdBtlPssRes: unknown;
    exclsSeen: unknown;
    inew: unknown;
    onew: unknown;
    offers: unknown;
    resources: {
      uid: string;
      regen: {
        count: number;
        begin: number;
        end: number;
        rate: unknown;
      };
    }[];
    achvs: unknown;
    titles: unknown;
    quEvBadges: {
      uid: string;
      rank: number;
      expireAt: number;
    }[];
    tknItms: unknown;
    tknItmsHist: unknown;
    ofrHist: unknown;
    dealHist: unknown;
    gsRes: unknown;
    vslots: unknown;
    objs: unknown;
    objsHist: unknown;
    trades: unknown;
    custOpts: unknown;
    snews: unknown;
    cnews: unknown;
    floors: unknown;
    walls: unknown;
    beams: unknown;
    txgid: unknown;
    captures: unknown;
    fusions: unknown;
    fullMoons: unknown;
    battlePassTasks: unknown;
    toInitBattlePassTasks: unknown;
    fusionPityTier: unknown;
    featureSeeds: {
      uid: string;
      seed: string;
    }[];
    stNodes: unknown;
  };
  city: {
    _id: string;
    name: unknown;
    popLimit: number;
    netwt: number;
    activity: number;
    quEvId: unknown;
    steamChatGroupId: unknown;
    members: {
      _id: string;
      name: string;
      level: number;
      rank: number;
      joined: number;
      lot: number;
      quEvComp: number;
      quEvCompBought: number;
      quEvId: unknown;
      online: boolean;
      lastLogin: number;
      title: unknown;
      cust: {
        gnd: string;
        cust: {
          bdyTyp: number;
          bdyScl: string;
          hrCut: string;
          brd: string;
          mst: string;
          eyeClr: string;
          hrClr: string;
          skClr: string;
          shrClr: string;
          pntClr: string;
          fclExpr: string;
        };
        hat: string;
        hatClr: string;
        srtClr2: string;
        armor: string;
        shoes: string;
        shoesClr: string;
        cloak: string;
        weapon: string;
        gloves: string;
        glovesClr: string;
        face: string;
        pants: string;
      };
      petCust: {
        head: string;
        body: string;
      };
      help: {
        expand: boolean;
        expandRecv: number;
        expandFrom: unknown;
        expandData: unknown;
        expandPaid: unknown;
        bExpand: boolean;
        bExpandRecv: number;
        bExpandFrom: unknown;
        bExpandData: unknown;
        bExpandPaid: unknown;
        fUpgrade: boolean;
        fUpgradeRecv: number;
        fUpgradeFrom: unknown;
        fUpgradeData: unknown;
        fUpgradePaid: unknown;
        fUpgrade2: boolean;
        fUpgrade2Recv: number;
        fUpgrade2From: unknown;
        fUpgrade2Data: unknown;
        fUpgrade2Paid: unknown;
      };
      lban: number;
      netwt: number;
      friends: unknown;
      quEvParty: unknown;
      quEvBoosters: unknown;
      quEvCompByCycle: unknown;
      quEvItemDonations: unknown;
    }[];
    mailboxes: {
      uid: string;
      wid: number;
      content: unknown;
    }[];
    investments: unknown;
    buildings: {
      uid: string;
      level: number;
      minLevel: number;
      nextAt: number;
    }[];
    settings: {
      join: number;
      minLevel: number;
      lang: string;
      pick: unknown;
      pickNext: number;
      message: unknown;
    };
    board: {
      bounties: unknown;
      prevContributors: unknown;
      currency: number;
      endsAt: number;
      nextUpdateAt: number;
      nextUpdateIn: number;
      endsIn: number;
    };
    upgrades: {
      uid: string;
      level: number;
    }[];
    boosts: unknown;
  };
};

type Titan = {
  name: string;
  city: string;
  adv: {
    id: number;
    name: string;
    aseed: number;
    level: number;
    cust: {
      bdyTyp: number;
      bdyScl: string;
      hrCut: string;
      brd: string;
      mst: string;
      eyeClr: string;
      hrClr: string;
      skClr: string;
      shrClr: string;
      pntClr: string;
      fclExpr: string;
    };
    xp: number;
    ready: number;
    qlast: number;
    rduration: number;
    cls: string;
    gnd: string;
    skl1: string;
    skl2: string;
    skl3: string;
    skl4: string;
    satk: number;
    sdef: number;
    shp: number;
    hpSeeds: number;
    atkSeeds: number;
    defSeeds: number;
    items: {
      id: number;
      uid: string;
      sid: number;
      tag1?: string;
      tag2: string;
      tag3: string;
    }[];
    transmogs: unknown;
  };
};
